### ISSUE TITLE
The engine dies when an activity resumed on android

### ISSUE THREAD

**Issue by gjslkjs** [elnormous/ouzel#20]
On the android, the engine dies when an activity with an engine view is paused and resumed.

Can you have any solution about this problem?

**Comment by elnormous** [comment]
Yes, this is because the OpenGL context is being dropped by Android. I am working on this issue (will recreate the context and reload all the resources)

**Comment by gjslkjs** [comment]
Thank you for you kind answer. 
Can you inform to me about whether it will fix soon or not?

**Comment by elnormous** [comment]
I am now in a process of rewriting the graphics resource initialization code. When I am done with that, I will also implement resource reloading in the case of a context loss. I hope to do that this week.

**Comment by elnormous** [comment]
This issue is now fixed, EGL context is now recreated after being lost on Android.
