### ISSUE TITLE
No script VM support?

### ISSUE THREAD

**Issue by TheOrneryNerd** [elnormous/ouzel#22]
Hi, I was just inspecting the engine, great work! 
Just a tiny question, why haven't you included a built in script support (a VM) inside the engine for languages like Lua or Python?

Would love to hear your thoughts about this feature possibility in the engine.

Keep up the great job,
Ron

**Comment by elnormous** [comment]
There are a couple of reasons why I don't want to pollute the code with VM's:
1. I want the engine to stay as close to the metal as possible (and sane)
2. Everybody has their own favorite language, so there is no clear choice what to add. Should I add all of them? Lots of people like Lua (and it is the most popular one), so I guess Lua would be the first choice but I hate it (arrays starting at 1, weird syntax etc.). Anybody can add bindings for their favorite scripting language to the engine if they want.
3. I am writing my games exclusively in C++ and I love it, so I don't need VM's.
4. I don't have time for it.
