### ISSUE TITLE
problem with lua binding

### ISSUE THREAD

**Issue by boruis** [elnormous/ouzel#24]
hi, i am trying to export lua binding with ouzel, using https://github.com/satoren/kaguya library. 
and i have big step, 80% completed.    
but there is problem i can't solve, becouse kaguya can't recognized member function and static member function when they have same name.  
 for example, Vector2::add and static Vector2::add
so  i came to get your help.  if you can change the static api name or some other way to solve this problem.

thanks for your attention.

**Comment by boruis** [comment]
and here is my test code: https://github.com/boruis/ouzel   there is a luabinding branch.

**Comment by karliss** [comment]
Did you tried to disambiguate the function pointer?
```c++
struct S {
    static int foo(int a) { return a; }
    int m;
    int foo() { return m;  }
    long long foo(long long x) { return x; }
};
int bar() {
    auto fptr = static_cast<int(*)(int)>(&S::foo);
    return fptr(1);
}
int foobar() {
    auto fptr = static_cast<int(S::*)()>(&S::foo);
    return (S{3}.*fptr)();
}
long long foooverload() {
    auto fptr = static_cast<long long(S::*)(long long)>(&S::foo);
    return (S{3}.*fptr)(9);
}
```

**Comment by boruis** [comment]
yes, function pointer can solve this problem.  thanks karliss.

**Comment by boruis** [comment]
yet there is another problem, following code will cause a compile error: 
use of undeclared identifiter 'T'.
`auto removeComponentPtr2 = static_cast<void(ouzel::scene::Actor::*)(const std::unique_ptr< T > &component)>(&ouzel::scene::Actor::removeComponent);`

**Comment by boruis** [comment]
here is the code file:
https://github.com/boruis/ouzel/blob/luabinding/luabinding/ouzel_scene_Actor_lua.cpp

**Comment by karliss** [comment]
Please don't be discouraged but I have a feeling that you have bunch of C++ to learn before you can tackle this. Not all C++ features can be directly translated as you are trying to do it. Some constructions will require more creative code, possibly some wrapper code. Few things that you need to do:
* Learn enough C++ so that you can understand C++ language features used by ouzel
* Learn what memory management functionality is provided by kaguya
* Understand what memory management approach is by ouzel
* Come up with a way to combine ouzel memory management with functionality available in kaguya

**Comment by boruis** [comment]
ok，i will take sometime to learn about what you said, thanks anyway.    if someone else like me want lua binding with ouzel engine can continue my work.

**Comment by boruis** [comment]
`use of undeclared identifiter 'T'   `this error was solved by add `template <typename T>` before the binding function start.
but another compile error occured:
`error: call to implicitly-deleted copy constructor of 'std::__1::unique_ptr<ouzel::scene::Animator, std::__1::default_delete<ouzel::scene::Animator> >'`

**Comment by boruis** [comment]
finally, i finished the luabinding by filter out the args with unique_ptr.
