### ISSUE TITLE
Missed CoInitializeEx before call CoCreateInstance.

### ISSUE THREAD

**Issue by Commondor** [elnormous/ouzel#27]
In function handleDeviceConnect(const DIDEVICEINSTANCEW* didInstance) missed CoInitializeEx before call CoCreateInstance:

	HRESULT hres = CoInitializeEx(NULL, COINIT_APARTMENTTHREADED);
	if (FAILED(hres))
	{
		LOG_ERROR_F( "CoInitializeEx() failure:" , (unsigned long)hres );
		return;
	}

**Comment by elnormous** [comment]
CoInitializeEx has to be called once and it is being done here:
https://github.com/elnormous/ouzel/blob/master/ouzel/core/windows/EngineWin.cpp#L69
