### ISSUE TITLE
[Question] Dynamic scenes

### ISSUE THREAD

**Issue by TheOrneryNerd** [elnormous/ouzel#29]
Hi, I notice that for each scene you actually create a source file (hpp and cpp).
Is it possible to have scene loading dynamically, let's say, from file:
for example, I have 1 text file containing all the scenes for example. Scenes.txt:

level_1,
level_2,
level_3

and to load them dynamically from the engine.

Would be more than happy to hear from you

**Comment by elnormous** [comment]
Yes, I am working on a scene editor and scene serialization right now.

**Comment by TheOrneryNerd** [comment]
That’s great - thank you!
Would be great to see a working example for both map editor and dynamic scene generation.
