### ISSUE TITLE
can't start because XINPUT1_4.dll is missing , in windows 7 64bit using VS2013

### ISSUE THREAD

**Issue by meiry** [elnormous/ouzel#3]
Im getting this error while compiling the examples 
according to this : https://msdn.microsoft.com/en-us/library/windows/desktop/hh405051(v=vs.85).aspx
XINPUT1_4.dll ships only windows 8 
![xinput](https://cloud.githubusercontent.com/assets/1107316/14179613/614a09e0-f768-11e5-8a04-b5dd87bcd117.png)

**Comment by elnormous** [comment]
Thanks for reporting this. Fixed it by using XInput 9.1.0. Commit: https://github.com/elvman/ouzel/commit/a7d6a65b84f0dc145a298ad081eb4289bb8b9bb1

**Comment by meiry** [comment]
Now there is new runtime error 
coming from Sprite.cpp: 

```
 bool Sprite::loadSpriteSheet(const std::string& filename, bool mipmaps)
        {
            File file(filename, File::Mode::READ, false);

            if (!file)
            {
                log("Failed to open %s", filename.c_str());
                return false;
            }

```

![assre](https://cloud.githubusercontent.com/assets/1107316/14189664/29955a84-f797-11e5-8a02-3628b5fd10e4.png)

**Comment by elnormous** [comment]
Please try running the sample project now. I added Resources directory to search path, so that the executable can load all the resources needed.
