### ISSUE TITLE
A lot of reallocations in vector assign a data.

### ISSUE THREAD

**Issue by Commondor** [elnormous/ouzel#34]
In function

     bool FileSystem::readFile(const std::string& filename, std::vector<uint8_t>& data, bool searchResources) const;

... is a lot of reallocations in a vector:

         data.assign(std::istreambuf_iterator<char>(file), std::istreambuf_iterator<char>());

Need append a code resize before assign.

For example:
	std::streampos fileSize = file.tellg();
	file.seekg(0, std::ios::end);
	fileSize = file.tellg() - fileSize;
	data.resize(fileSize);
	file.seekg(0, std::ios_base::beg);

A vector resize will speed up file uploading in 10 times in the debug mode.

**Comment by elnormous** [comment]
I had a plan to rewrite the file reading code so I didn't touch it. But thanks, this is now fixed.
