### ISSUE TITLE
WASAPI Audio backend

### ISSUE THREAD

**Issue by amerkoleci** [elnormous/ouzel#36]
Any plans to add WASAPI for Audio?
I'm adding it into my game engine (https://github.com/amerkoleci/alimer).
I saw also you are reading entire file for audio stream, while instead you should stream chunk of audio file during audio streaming.

**Comment by elnormous** [comment]
No, not currently. Ouzel audio engine already has XAudio 2, DirectSound and OpenAL backends.

**Comment by amerkoleci** [comment]
I see, its ok, if you have time check my engine and if you have any suggestion you're welcome :)
