### ISSUE TITLE
Use of angle brackets around file names for include statements

### ISSUE THREAD

**Issue by elfring** [elnormous/ouzel#4]
Would you like to [replace any double quotes](https://github.com/elnormous/ouzel/blob/2e653d3ef375e780f8ec3e2eb870fe979cea1e82/ouzel/ouzel.h#L6) by [angle brackets around file names for include statements](http://stackoverflow.com/questions/21593/what-is-the-difference-between-include-filename-and-include-filename)?

**Comment by elnormous** [comment]
No, please read C or C++ standard. Angle brackets are compiler-dependent and are not meant to be used for user's files.

**Comment by elfring** [comment]
I suggest to reconsider the consequences of [the following wording](http://c0x.coding-guidelines.com/6.10.2.html) from [the section "16.2 Source file inclusion"](http://open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3797.pdf) in the standard specification for the programming language "C++".

```
…
The named source file is searched for in an implementation-defined manner. If this search is not supported, or if the search fails, the directive is reprocessed as if it read

#include <h-char-sequence> new-line
…
```
- How do you think about to avoid "a duplicated file search" here?
- Would you like to [restrict the searched directories](https://gcc.gnu.org/onlinedocs/cpp/Include-Syntax.html) for header files of your software?

**Comment by elnormous** [comment]
Yes, angle brackets are meant for "named sources" not filenames and as I said they are compiler-defined.
1. Why do I need to avoid that? There should be no such thing as duplicate files;
2. It is already restricted to the "core" directory.

**Comment by elfring** [comment]
There are different opinions about the handling of the involved implementation-defined behaviour.
- Will header files be also searched outside the specified include directories if double quotes are used for the discussed preprocessor statement?
- Is there a speed difference measurable if a file is not found there and the search will be retried with "the angle brackets inclusion method"?

**Comment by elnormous** [comment]
Can you please share those opinions? There is no rule that forces compilers to include files with angle brackets (named sources can be anything, even source downloaded from internet at compile-time). Of course, usually angle brackets will be faster, because it will search in the "-include" directories, but I care about cross-compiler support and following the standard more than tiny compiler speed optimizations.

**Comment by elfring** [comment]
How much do you care where the include files are safely stored for a software library?

**Comment by elnormous** [comment]
What do you mean by "safely"? They are safely stored the "core" subdirectory of the repository. What is the unsafe part about this?

**Comment by elfring** [comment]
I would generally prefer to exclude the potential for the inclusion of header files from unexpected directories. Can such a security detail become a bit more important occasionally?

**Comment by elnormous** [comment]
Do you want to protect yourself against somebody creating files like CompilerConfig.h in the core subdirectory of your project and messing it up (because that is almost impossible to happen unintentionally)?

**Comment by elfring** [comment]
It seems that I have got software development concerns in such a direction because of the potential confusion from inclusion of headers from "local" and other "known" directories.

I find it important to be reasonably sure that the desired computations were really correct because it could be determined by the applied software build parameters that the used functions were actually derived from the expected source files. Can you follow this design concern?

**Comment by elnormous** [comment]
Yes, I follow you, and the solution to your "problem" could be to move all the includes to the "ouzel" directory, so that you have to include "ouzel/core/CompilerConfig.h". This will make the filename conflict almost impossible.

**Comment by elfring** [comment]
How do you think about to achieve a bit more confidence that only appropriate parts of a software library (like "ouzel") were included in a specific application?

**Comment by elnormous** [comment]
Actually, if you include only ouzel.h, then all the other header files will be searched relatively to the ouzel.h. So, even if you create a file core/CompilerConfig.h in the root directory of your project, by including only ouzel.h in your source you are safe against filename conflicts.

**Comment by elfring** [comment]
Are there any risks that the local version of a "ouzel.h" (or related header file) from a project development directory will resolve to an inappropriate (perhaps outdated) variant while the revision in a "blessed" system directory provides a higher level of confidence?

**Comment by elnormous** [comment]
If you are afraid of somebody creating ouzel.h in your local directory, then include it with angle brackets (#include &lt;ouzel.h&gt;) and you will be safe.

**Comment by elfring** [comment]
How will the situation evolve if only parts would be included from your software library?

**Comment by elnormous** [comment]
Don't include parts of it, just include "ouzel.h" and everything will be fine.

**Comment by elfring** [comment]
Are there any plans to split the software library into more components?

**Comment by elnormous** [comment]
Currently not.
