### ISSUE TITLE
Rasp pi 4 compilation error

### ISSUE THREAD

**Issue by TheMaverickProgrammer** [elnormous/ouzel#49]
Let me know if I'm missing `make` arguments. According to the docs, there should be a `build` directory but I am not seeing that. I tried running `make` anyway and get these errors:

```
 make
make -C engine DEBUG= PLATFORM= VC_DIR= 
make[1]: Entering directory '/home/pi/Code/ouzel/engine'
g++ -c -x c++  -std=c++17 -Wall -Wpedantic -Wextra -Wshadow -Wdouble-promotion -Woverloaded-virtual -Wold-style-cast -I"../shaders" -I"../external/khronos" -I"../external/smbPitchShift" -I"../external/stb" -O3 -include pch/cpp/Prefix.h -MMD -MP core/Window.cpp -o core/Window.o
In file included from core/Window.cpp:21:
core/linux/NativeWindowLinux.hpp:12:12: fatal error: bcm_host.h: No such file or directory
```
I have mesa, opengl, and dev lib packages installed already that are commonly used for pi development.

**Comment by elnormous** [comment]
I fixed the build in https://github.com/elnormous/ouzel/commit/1b757fe9bed794e04f5cdef81fc043155fd9f0bd, https://github.com/elnormous/ouzel/commit/b7aba93b5d1c1a9260fd49682054248350542860, and https://github.com/elnormous/ouzel/commit/1f611ca559aac5370b1f8f2f7390dd860f39701b and added instructions in https://github.com/elnormous/ouzel/commit/527b48d2470b3bdec1b0bccef072867f51756ac4.

**Comment by TheMaverickProgrammer** [comment]
Thank you for being awesome!
